apiVersion: apps/v1

kind: Deployment

metadata:
  name: movie

spec:
  replicas: 2

  selector:
    matchLabels:
      app: movie

  template:
    metadata:
      labels:
        app: movie

    spec:
      containers:
        - name: movie
          image: sebbiemzing/movie:1.0.0
          imagePullPolicy: Always

          ports:
            - containerPort: 8083
